# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bobecar/VESC_Embedded_Linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bobecar/VESC_Embedded_Linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bobecar/VESC_Embedded_Linux/CMakeFiles /home/bobecar/VESC_Embedded_Linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bobecar/VESC_Embedded_Linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vesc_uart_app

# Build rule for target.
vesc_uart_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vesc_uart_app
.PHONY : vesc_uart_app

# fast build rule for target.
vesc_uart_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/build
.PHONY : vesc_uart_app/fast

bldc.o: bldc.cpp.o
.PHONY : bldc.o

# target to build an object file
bldc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc.cpp.o
.PHONY : bldc.cpp.o

bldc.i: bldc.cpp.i
.PHONY : bldc.i

# target to preprocess a source file
bldc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc.cpp.i
.PHONY : bldc.cpp.i

bldc.s: bldc.cpp.s
.PHONY : bldc.s

# target to generate assembly for a file
bldc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc.cpp.s
.PHONY : bldc.cpp.s

bldc_interface.o: bldc_interface.c.o
.PHONY : bldc_interface.o

# target to build an object file
bldc_interface.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc_interface.c.o
.PHONY : bldc_interface.c.o

bldc_interface.i: bldc_interface.c.i
.PHONY : bldc_interface.i

# target to preprocess a source file
bldc_interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc_interface.c.i
.PHONY : bldc_interface.c.i

bldc_interface.s: bldc_interface.c.s
.PHONY : bldc_interface.s

# target to generate assembly for a file
bldc_interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc_interface.c.s
.PHONY : bldc_interface.c.s

bldc_interface_uart.o: bldc_interface_uart.c.o
.PHONY : bldc_interface_uart.o

# target to build an object file
bldc_interface_uart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc_interface_uart.c.o
.PHONY : bldc_interface_uart.c.o

bldc_interface_uart.i: bldc_interface_uart.c.i
.PHONY : bldc_interface_uart.i

# target to preprocess a source file
bldc_interface_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc_interface_uart.c.i
.PHONY : bldc_interface_uart.c.i

bldc_interface_uart.s: bldc_interface_uart.c.s
.PHONY : bldc_interface_uart.s

# target to generate assembly for a file
bldc_interface_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/bldc_interface_uart.c.s
.PHONY : bldc_interface_uart.c.s

buffer.o: buffer.c.o
.PHONY : buffer.o

# target to build an object file
buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/buffer.c.o
.PHONY : buffer.c.o

buffer.i: buffer.c.i
.PHONY : buffer.i

# target to preprocess a source file
buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/buffer.c.i
.PHONY : buffer.c.i

buffer.s: buffer.c.s
.PHONY : buffer.s

# target to generate assembly for a file
buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/buffer.c.s
.PHONY : buffer.c.s

comm_uart.o: comm_uart.c.o
.PHONY : comm_uart.o

# target to build an object file
comm_uart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/comm_uart.c.o
.PHONY : comm_uart.c.o

comm_uart.i: comm_uart.c.i
.PHONY : comm_uart.i

# target to preprocess a source file
comm_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/comm_uart.c.i
.PHONY : comm_uart.c.i

comm_uart.s: comm_uart.c.s
.PHONY : comm_uart.s

# target to generate assembly for a file
comm_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/comm_uart.c.s
.PHONY : comm_uart.c.s

crc.o: crc.c.o
.PHONY : crc.o

# target to build an object file
crc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/crc.c.o
.PHONY : crc.c.o

crc.i: crc.c.i
.PHONY : crc.i

# target to preprocess a source file
crc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/crc.c.i
.PHONY : crc.c.i

crc.s: crc.c.s
.PHONY : crc.s

# target to generate assembly for a file
crc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/crc.c.s
.PHONY : crc.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/main.cpp.s
.PHONY : main.cpp.s

packet.o: packet.c.o
.PHONY : packet.o

# target to build an object file
packet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/packet.c.o
.PHONY : packet.c.o

packet.i: packet.c.i
.PHONY : packet.i

# target to preprocess a source file
packet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/packet.c.i
.PHONY : packet.c.i

packet.s: packet.c.s
.PHONY : packet.s

# target to generate assembly for a file
packet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/packet.c.s
.PHONY : packet.c.s

timers.o: timers.c.o
.PHONY : timers.o

# target to build an object file
timers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/timers.c.o
.PHONY : timers.c.o

timers.i: timers.c.i
.PHONY : timers.i

# target to preprocess a source file
timers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/timers.c.i
.PHONY : timers.c.i

timers.s: timers.c.s
.PHONY : timers.s

# target to generate assembly for a file
timers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vesc_uart_app.dir/build.make CMakeFiles/vesc_uart_app.dir/timers.c.s
.PHONY : timers.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vesc_uart_app"
	@echo "... bldc.o"
	@echo "... bldc.i"
	@echo "... bldc.s"
	@echo "... bldc_interface.o"
	@echo "... bldc_interface.i"
	@echo "... bldc_interface.s"
	@echo "... bldc_interface_uart.o"
	@echo "... bldc_interface_uart.i"
	@echo "... bldc_interface_uart.s"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... comm_uart.o"
	@echo "... comm_uart.i"
	@echo "... comm_uart.s"
	@echo "... crc.o"
	@echo "... crc.i"
	@echo "... crc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... packet.o"
	@echo "... packet.i"
	@echo "... packet.s"
	@echo "... timers.o"
	@echo "... timers.i"
	@echo "... timers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

